project:
  type: website
  output-dir: docs
  resources:
    - ads.txt
website:
  favicon: "content/img/clidewo-favicon.png"
  site-url: https://github.com/edgarodriguez/rodriguez-huerta-website
  repo-url: https://github.com/edgarodriguez/rodriguez-huerta-website
  open-graph: true
  draft-mode: visible
  navbar:
    pinned: true
    logo: "content/img/logo_yellow3.png"
    background: primary
    right:
      - href: about.qmd
      - href: publications.qmd
      - text: Datavis #change html index.pt to Recursos"
        menu:
          - href: datavis.qmd
          - href: other-resources.qmd
      - text: Portfolio #change html index.pt to Recursos"
        menu:
          - href: resources.qmd
          - href: literature-tools.qmd
          - href: other-resources.qmd
      - href: blog.qmd
      - href: talks.qmd
      - text: CV
        href: cv.qmd      

  page-footer:
    background: black
    left: © Copyright 2024 CC-BY-NC, Edgar Rodríguez-Huerta
    right: Some text
  google-analytics: "G-RG1R3XP26Q"
#  cookie-consent:
#    type: express
#    style: headline
#    palette: dark
#  announcement:
#    icon: info-circle
#    dismissable: true
#    content: "COMING SOON: Subscribe to our newsletter to be updated on project progress / EM BREVE: Assine nosso boletim informativo para ser atualizado sobre o andamento do projeto"
#    type: success
#    position: below-navbar

format:
  html:
    theme: flatly
    css: clidewo_theme.css
    toc: true
    code-overflow: scroll
adsense:
  publisher-id: ca-pub-8824987846194517
filters:
- adsense